import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../common/styles/globals.css'
import Navbar from '@/common/module/navbar'
import {SessionProvider} from 'next-auth/react'
import Session from '@/common/libs/Session'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Todo List',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Session>
        <div>
          <Navbar/>
        </div>
        {children}
        </Session>
        </body>
    </html>
  )
}


